### ISSUE TITLE
最新的commit无法编译

### ISSUE THREAD

**Issue by heheda123123** [Eason0210/build-emacs#2]
最新commit无法编译，会提示 bootstrap pdmp 127啥的
https://github.com/emacs-mirror/emacs/commit/eedb7111185569e426726fe15242f8ba08f89b31

reset到前一天的commit 就可以编译通过
https://github.com/emacs-mirror/emacs/commit/600b90ed56854e8460038ca6b8aaa1feae4ab2c9

这种一般是emacs自身的问题把？等他修复就行？貌似是从emacs-29分支合并过来的代码有问题

**Comment by Eason0210** [comment]
最近 master 的编译是有问题。不过最新的 commit 已经可以正常编译了。我在 Windows 10 下编译了 Emacs master 是可以的。

```sh
 ./build-emacs.sh master --with-native-compilation=aot
```

GNU Emacs 30.0.50 (build 1, x86_64-w64-mingw32, git sha1 9c282faf26e) of 2023-07-09

https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=9c282faf26eb517532508d466270b7b97d436c70
