### ISSUE TITLE
文档可以补充下depth=1，另外之前为了解决gcc编译不了加的编译参数也可以去掉了

### ISSUE THREAD

**Issue by heheda123123** [Eason0210/build-emacs#3]
文档里面的可以加个`--depth=1`，clone下来的文件会小很多
```
git clone https://git.savannah.gnu.org/git/emacs.git ~/src/emacs
```
另外脚本里CFLAGS的`-fno-optimize-sibling-calls`也可以去掉了，试了下最新commit貌似修复问题不用加这个参数了

**Comment by Eason0210** [comment]
这个脚本是支持选择指定的 commit 进行编译的，全部 clone 是为了方便每次拉取新的 commit 时不要拉取整个仓库。如果需要  --depth=1，可以自己改一下。

CFLAGS的-fno-optimize-sibling-calls 我这边还是需要的，不然还是会报错。这个问题是因为 msys 上的 GCC 13.1 造成的，不是 Emacs 本身的问题。所以要等以后 GCC 在 Msys上改进才有可能解决。

**Comment by heheda123123** [comment]
老哥你msys里面的gcc更新了嘛？我这里更新到最新之后，不加那个参数是可以编译成功的

**Comment by Eason0210** [comment]
> 老哥你msys里面的gcc更新了嘛？我这里更新到最新之后，不加那个参数是可以编译成功的

我是更新到最新了，不过我最近尝试编译的是 emacs 29，目前还没时间编译 emacs 30. 因为我现在主要使用 emacs 29，Emacs 30 最近不大稳定。

我使用的编译参数：
```
./build-emacs.sh emacs-29 --with-native-compilation=aot 
```

你编译 emacs 30 的 native-compilation 时不需要加 `-fno-optimize-sibling-calls`  可能是因为上游已经加了 workaround。
